# Generated by Django 3.0.3 on 2021-05-03 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('1', 'Procedure'), ('2', 'Prescription'), ('3', 'Testing')], default='1', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'ordering': ['patient_id'],
            },
        ),
        migrations.CreateModel(
            name='PhysicianSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physician_id', models.CharField(max_length=3, unique=True)),
                ('speciality_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PatientTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.EventCategory')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Patient')),
                ('physician_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PhysicianSpeciality')),
            ],
        ),
    ]
