# Generated by Django 3.0.3 on 2021-05-05 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientlog',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='patientlog',
            name='patient_id',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='PatientLog',
        ),
    ]
