# Generated by Django 3.0.3 on 2021-05-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210505_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('patient_id', models.CharField(max_length=3)),
            ],
        ),
    ]
